first commit
Vakhaa/altexsoft-lab-2020 pull request #1
Opened 2020-08-13 18:41 UTC by Vakhaa

Надеюсь, в этот раз я сделал все верно)

2020-08-17 11:34 UTC, alex-geraschenko requested changes
1. Разнесите методы задач по разным классам в соответствии с принципами SOLID
2. Разнесите классы по разным файлам: 1 класс - 1 файл
3. Постарайтесь уйти от дублирования кода

2020-08-17 11:34 UTC, alex-geraschenko commented on Task1/Program.cs
> +            int i = str.Length - 1;
Обратите внимание на существующие методы `ToCharArray` и `Reverse`

2020-08-17 11:34 UTC, alex-geraschenko commented on Task1/Program.cs
> +        public static string[] Reverse(this String[] str, int StartIndex)
В C# аргументы методов принято называть в `camelCase`

2020-08-17 11:34 UTC, alex-geraschenko commented on Task1/Program.cs
> +        private String[] m_Text;
В C# приватные поля принято назвать в `camelCase`. Еще, для удобства чтения кода, добавляют `_` вначале

2020-08-17 11:34 UTC, alex-geraschenko commented on Task1/Program.cs
> +        public String[] Text {  get {return m_Text;} }
Лучше использовать авто-свойства

2020-08-21 16:20 UTC, alex-geraschenko requested changes
1. Не все задачи разнесены по разным классам
2. Логика намешана и размазана по разным классам, а должна быть структурирована обобщена, где возможно
3. Не стоит использовать `out` параметры
4. Каждый класс и интерфейс должны быть в отдельных файлах
5. Перенесите папку `Task1.BL` внутрь папки `Task1`

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/ConsolManager.cs
> +        private void WorkWithFile(IReadTxt read, out string str)
Постарайтесь не использовать `out` параметры

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/ConsolManager.cs
> +                            if (str == "yes" | str == "y" | str == "Y" | str == "Yes" | str == "YES")
Постарайтесь упростить это выражение. Обратите внимание на `ToLower()` метод у строки

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/ConsolManager.cs
> +        private void OpenFile(IReadTxt read, out string str)
Постарайтесь не использовать `out` параметры

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/ConsolManager.cs
> +            if (_fileText.Text[0] == "No" & _fileText.Text[1] == "file" & _fileText.Text[4] == "name")
Используйте `&&` вместо `&`

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/ConsolManager.cs
> +                _reader = null; Console.ReadKey(); str = ""; return;
Каждое выражение должно быть отдельной строчкой для улучшения читаемости кода

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/ConsolManager.cs
> +        public void Walk(out String str)
Постарайтесь не использовать `out` параметры

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/ConsolManager.cs
> +        public void Walk(out String str)
Этот метод делает слишком много одновременно. Нарушает принцип Single Responsibility

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/Reader.cs
> +            this._path = path;
В данном слечае нет необходимости использовать `this`

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/Reader.cs
> +                using (FileStream fstream = File.OpenRead(_path))
Обратите внимание на `File.ReadAllText`

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/Reader.cs
> +            using (FileStream fstream = new FileStream(CutFileName(_path) + "~" + FileName, FileMode.OpenOrCreate))
Обратите внимание на `File.WriteAllText`

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/StaticString.cs
> +        public static string[] Reverse(this String[] str, int startIndex)
Есть встроенные средства для переворачивания строки. Посмотрите на `ToCharArray` и `Array.Reverse`

2020-08-21 16:20 UTC, alex-geraschenko commented on Task1.BL/WalkerDirectories.cs
> +            ChangeDisk(out String str);
Задачи смены дисков не было

2020-08-21 19:23 UTC, Vakhaa commented on Task1.BL/WalkerDirectories.cs
> +            ChangeDisk(out String str);
Это для того, что бы можно было выбрать файл не только вводя полный путь. А выбрав диск, директорию и там файл.
И изначально программа предлагает выбрать диск, что бы начать с конкретной директории.

2020-08-26 07:59 UTC, alex-geraschenko requested changes

2020-08-26 07:59 UTC, alex-geraschenko commented on Task1/Task1.BL/Reader.cs
> +            for (int i = path.Length - 1; i > 0; i--)  //обрезаем от пути название файла
Обратите внимание на статические методы из `System.IO.Path`

2020-08-26 07:59 UTC, alex-geraschenko commented on Task1/Task1.BL/ConsolManager.cs
> +        public string getPath()
Имена методов принято называть в `PascalCase`

2020-08-26 07:59 UTC, alex-geraschenko commented on Task1/Task1.BL/ConsolManager.cs
> +        private static bool isExite()
Имена методов принято называть в `PascalCase`

2020-08-26 07:59 UTC, alex-geraschenko commented on Task1/Task1.BL/TextWorker.cs
> +    public class TextWorker
Этот класс содержит в себе методы для всех задач по работе с текстом из задания, а должны быть отдельные классы для каждой задачи

2020-08-26 07:59 UTC, alex-geraschenko commented on Task1/Task1.BL/ConsolManager.cs
> +            _walker = new WalkerDirectories(); //инициализация папок и файлов
Нарушение принципа **Dependency Inversion**

2020-08-27 16:16 UTC, alex-geraschenko requested changes

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/Interfaces/IWalkerDirectories.cs
> +        public void SetDireketories(string path);
Опечатка

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ClassForText/DeleteStringOrChar.cs
> +    public static class DeleteStringOrChar
Имя класса должно быть сушествительным и отображать назначение этого класса

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ClassForText/DeleteStringOrChar.cs
> +            if (str.Length == 1) //Symbols
Методы `DeleteSymbol` и `DeleteWord` можно объединить

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ClassForText/EveryTenерWord.cs
> +    public static class EveryTenерWord
Опечатка в имени класса

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ClassForText/EveryTenерWord.cs
> +    public static class EveryTenерWord
Имя класса должно быть сушествительным и отображать назначение этого класса

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ClassForText/Reverse.cs
> +    public static class Reverse
Имя класса должно быть сушествительным и отображать назначение этого класса

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ClassForText/Reverse.cs
> +        public static void ThirdSentenceReverse(String text)
Имя метода должно быть в глагольной форме

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ClassForText/Reverse.cs
> +        public static void ThirdSentenceReverse(String text)
Используйте `string` вместо `String`

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ConsolManager.cs
> +        public string GetPath()
Можно заменить на свойство

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/Interfaces/IReadTxt.cs
> +        public void CreateFile(string text);
Имя интерфейса не соответствует его содержанию

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/TextWorker.cs
> +        public String[] Text { get; }
Используйте `string` вместо `String`

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/TextWorker.cs
> +            Text = text.Split(new char[] { ' ' });
А зачем разбивать текст ?

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ConsolManager.cs
> +                            if (_reader == null) _reader = new Reader(str);
Какой смысл все время пересоздвавать `Reader` на уровне всего класса ?

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ConsolManager.cs
> +                            if (_reader == null) _reader = new Reader(_walker.Path + str);
Какой смысл все время пересоздвавать `Reader` на уровне всего класса ?

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ConsolManager.cs
> +                            if (_reader == null) _reader = new Reader(str);
Какой смысл все время пересоздвавать `Reader` на уровне всего класса ?

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/ConsolManager.cs
> +    public class ConsolManager
Этот класс нарушает принцип **Single Responsibility**

2020-08-27 16:16 UTC, alex-geraschenko commented on Task1/Task1.BL/WalkerDirectories.cs
> +    public class WalkerDirectories:IWalkerDirectories
Этот класс содержит сложную и запутаную логику. Нарушает принцип KIS

2020-08-28 11:27 UTC, Vakhaa commented on Task1/Task1.BL/ClassForText/Reverse.cs
> +        public static void ThirdSentenceReverse(String text)
> Имя метода должно быть в глагольной форме

Ага, то есть поставить Reverse  в начале названия будет достаточно ? ( ReverseThirdSentence )

2020-08-28 11:38 UTC, Vakhaa commented on Task1/Task1.BL/ClassForText/DeleteStringOrChar.cs
> +    public static class DeleteStringOrChar
> Имя класса должно быть сушествительным и отображать назначение этого класса

Подходящий ли вариант "RemoverFromText" ?

2020-08-28 13:08 UTC, Vakhaa commented on Task1/Task1.BL/ConsolManager.cs
> +    public class ConsolManager
> Этот класс нарушает принцип **Single Responsibility**

Не совсем понял почему. Файл собирает в себе логику других классов и занимается выводом её на консоль. Тем скрываю из вне всю логику приложения остовляя только методы вывода. Из -за этого **Main** выглядит очень компактно.

2020-08-28 13:19 UTC, Vakhaa commented on Task1/Task1.BL/TextWorker.cs
> +            Text = text.Split(new char[] { ' ' });
> А зачем разбивать текст ?

В некоторых методах проще работать с текстом, когда он разбит. И я решил, то бы не повторять код, раз разбить и сохранить.

2020-08-28 15:37 UTC, alex-geraschenko commented on Task1/Task1.BL/ConsolManager.cs
> +    public class ConsolManager
**Main** выглядит компактно, а **ConsolManager** нет.
В этом классе происходит и перемещение по каталогам, и отображение меню и работа с файлами. Это нарушает принцип **Single Responsibility**

2020-08-31 09:57 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-08-31 11:20 UTC, merged