Task/task2
Vakhaa/altexsoft-lab-2020 pull request #2
Opened 2020-08-21 01:27 UTC by Vakhaa

Task2

2020-08-21 07:54 UTC, serhii-shkodenko commented
Пожалуйста, уберите статус Draft с вашего пулл реквеста.

2020-08-21 10:16 UTC, Vakhaa commented
> Пожалуйста, уберите статус Draft с вашего пулл реквеста. Обозначьте, что он готов для ревью.

Сделал, но там еще первое задание не подтверждено.

2020-08-26 08:05 UTC, alex-geraschenko commented
Постарайтей реализовать шаблоны **Repository/UnitOfWork**

2020-08-26 17:09 UTC, alex-geraschenko requested changes
Постарайтей реализовать шаблоны **Repository/UnitOfWork**

2020-08-31 18:12 UTC, alex-geraschenko requested changes
1. Уберите файлы первого задания из пул реквеста
2. Уберите зависимость `RecipesControler` от других контроллеров

2020-08-31 18:12 UTC, alex-geraschenko commented on .gitignore
> +<<<<<<< HEAD
Конфликт мержа

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/CategoryControler.cs
> +            string str;
Объявлять переменную отдельно не нужно

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/CategoryControler.cs
> +            int categories;
Объявлять переменную отдельно не нужно

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/CategoryControler.cs
> +            string str;
Объявлять переменную отдельно не нужно

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.CMD/bin/Debug/netcoreapp3.1/ctgrs.json
> +"[\r\n  {\r\n    \"Name\": \"Первое блюдо\",\r\n    \"Subcategories\": [\r\n      \"Украинская кухня\",\r\n      \"Польская кухня\"\r\n    ],\r\n    \"CurrentSubcategories\": \"Украинская кухня\"\r\n
Папки `bin` в коммитах быть не должно

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.CMD/bin/Debug/netcoreapp3.1/igrdt.json
> +"[\r\n  {\r\n    \"Name\": \"Свиные ребра\"\r\n  },\r\n  {\r\n    \"Name\": \"Лук репчатый\"\r\n  },\r\n  {\r\n    \"Name\": \"Морковь\"\r\n  },\r\n  {\r\n    \"Name\": \"Свекла\"\r\n  },\r\n  {\r\n
Папки `bin` в коммитах быть не должно

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.CMD/bin/Debug/netcoreapp3.1/rcps.json
> +"[\r\n  {\r\n    \"Name\": \"Борщ гетманский\",\r\n    \"Category\": \"Первое блюдо\",\r\n    \"Subcategory\": \"Украинская кухня\",\r\n    \"Description\": \"Хотя все борщи хороши, но гетманский бор
Папки `bin` в коммитах быть не должно

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Model/Ingradient.cs
> +        public Ingradient(string Name)
Опечатка. Не `Ingradient`, а `Ingredient`

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Interfaces/IRecipeRepository.cs
> +        public GenericRepository<List<Recipe>, Recipe> RecipesRepository { get; }
Зачем это свойство?

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Interfaces/IRecipeRepository.cs
> +        public void Dispose();
Для этого метода есть специальный интерфейс `IDisposable`

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Interfaces/IIngradientRepository.cs
> +        public void Save(UnitOfWork uow);
Все, что объявляется в интерфейсе, публичное, поэтому модификаторы `public` тут не нужны

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Interfaces/IRecipeRepository.cs
> +        public void Save(UnitOfWork uow);
Все, что объявляется в интерфейсе, публичное, поэтому модификаторы `public` тут не нужны

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Interfaces/ICategoryRepository.cs
> +        public GenericRepository<List<Category>, Category> CategoryRepository { get; }
Зачем это свойство?

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Interfaces/ICategoryRepository.cs
> +        public void Save(UnitOfWork uow);
Все, что объявляется в интерфейсе, публичное, поэтому модификаторы `public` тут не нужны

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Interfaces/IIngradientRepository.cs
> +        public GenericRepository<List<Ingradient>, Ingradient> IngradientRepository { get; }
Зачем это свойство?

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Interfaces/IIngradientRepository.cs
> +        public void Dispose();
Для этого метода есть специальный интерфейс `IDisposable`

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Interfaces/ICategoryRepository.cs
> +        public void Dispose();
Для этого метода есть специальный интерфейс `IDisposable`

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/DAL/UnitOfWork.cs
> +    public class UnitOfWork : ICategoryRepository,IRecipeRepository, IIngradientRepository, IDisposable
`Repoitory` и `UnitOfWork` - это разные вещи и не стоит их лепить в одну кучу
Посмотрите тут пример реализации этих шаблонов https://www.infoworld.com/article/3107186/how-to-implement-the-repository-design-pattern-in-c.html

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/DAL/UnitOfWork.cs
> +            GC.SuppressFinalize(this);
Неполная реализация `Dispose`

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/DAL/GenericRepository.cs
> +        internal T _context;
Почему не `private`?

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/DAL/GenericRepository.cs
> +        internal string FILE_NAME;
Нарушение конвенции именования полей

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/IngradientControler.cs
> +        public void AddIngradients(out List<string> ingradients)
Не используйте `out` без острой необходимости. В данном случае можно обойтись без него

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/IngradientControler.cs
> +            _ingradientRepository.IngradientRepository.Insert(new Ingradient(nameIngradient) ?? throw new ArgumentNullException("Нельзя добавить пустой ингрендиент.", "ingradient"));
Такая запись бессмысленна. `new Ingredient` никогда не будет `null`

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/IngradientControler.cs
> +            for (int id=0; id<Ingradients.Get().Count;id++)
Попробуйте `Where` из `System.Linq`

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/JSONManager.cs
> +            JsonSerializer des = new JsonSerializer();
`JsonSerializer` лучше создавать в конструкторе, а `JSONManager` сделать не статическим

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/RecipesControler.cs
> +            var Recipes = _recipeRepository.RecipesRepository.Get();
Локальные переменные принято называть в `camelCase`

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/RecipesControler.cs
> +            string str;
Объявлять переменную отдельно не нужно

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/RecipesControler.cs
> +            string str;
Объявлять переменную отдельно не нужно

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/RecipesControler.cs
> +        public void AddRecipe(ref CategoryControler categoryControler, ref IngradientControler ingradientControler)
Зачем тут `ref`?

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/RecipesControler.cs
> +        public bool WalkRecipes(ref CategoryControler categoryControler)
Зачем тут `ref`?

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/RecipesControler.cs
> +        public void OpenRecipe(ref CategoryControler categoryControler, ref IngradientControler ingradientControler)
Зачем тут `ref`?

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Model/Recipe.cs
> +        public Recipe(string Name,string Category, string Subcategory,string Description, List<string> Ingredients,List<string> CountIngredients, List<string> StepsHowCooking)
Имена параметров должны быть в `camelCase`

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Model/Recipe.cs
> +                if (string.IsNullOrWhiteSpace(ingredient))
Посмотрите на методы `Any` или `All` из `System.Linq`

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Model/Recipe.cs
> +                if (string.IsNullOrWhiteSpace(count))
Посмотрите на методы `Any` или `All` из `System.Linq`

2020-08-31 18:12 UTC, alex-geraschenko commented on Task2/Task2.BL/Model/Recipe.cs
> +                if (string.IsNullOrWhiteSpace(steps))
Посмотрите на методы `Any` или `All` из `System.Linq`

2020-08-31 22:36 UTC, Vakhaa commented on Task2/Task2.BL/DAL/UnitOfWork.cs
> +    public class UnitOfWork : ICategoryRepository,IRecipeRepository, IIngradientRepository, IDisposable
Я не правильно назвал интерфейсы, отношения к  репозиториям они не имеют. Я сделал эти интерфейсы для того, что бы при передачи экземпляра UnityOfWork в контролеры их можно было апкастить до соответствующих интерфейсов, тем скрывая публичные свойства для других контролеров. А так же это позволяет использовать один метод Save в классе UnityOfWork.

2020-09-01 21:52 UTC, Vakhaa commented on Task2/Task2.BL/Interfaces/IRecipeRepository.cs
> +        public GenericRepository<List<Recipe>, Recipe> RecipesRepository { get; }
Я переназвал интерфейс как IRecipeUnityOfWork. К репозиторию этот интерфейс отношения не имел. В коде я делаю апкаст экземпляра класса  UnityOfWork и передавал в соответствующий контролер. В данном случае RecipeControler.
Это позволило скрыть свойства репозиториев для других классов. И сделать один метод Save для всех, а так же не перегружать его.

2020-09-01 21:54 UTC, Vakhaa commented on Task2/Task2.BL/Interfaces/IRecipeRepository.cs
> +        public GenericRepository<List<Recipe>, Recipe> RecipesRepository { get; }
А само свойство генерирует репозиторий при первом обращение и дальше хранит его.

2020-09-01 21:56 UTC, Vakhaa commented on Task2/Task2.BL/Interfaces/ICategoryRepository.cs
> +        public GenericRepository<List<Category>, Category> CategoryRepository { get; }
Я переназвал интерфейс как **ICategoryUnityOfWork**. К репозиторию этот интерфейс отношения не имел. В коде я делаю апкаст экземпляра класса **UnityOfWork** и передавал в соответствующий контролер. В данном случае **CategoryControler**.
Это позволило скрыть свойства репозиториев для других классов. И сделать один метод Save для всех, а так же не перегружать его.
А само свойство генерирует репозиторий при первом обращение и дальше хранит его.

2020-09-01 21:57 UTC, Vakhaa commented on Task2/Task2.BL/Interfaces/IIngradientRepository.cs
> +        public GenericRepository<List<Ingradient>, Ingradient> IngradientRepository { get; }
Я переназвал интерфейс как **IIngredientUnityOfWork**. К репозиторию этот интерфейс отношения не имел. В коде я делаю апкаст экземпляра класса **UnityOfWork** и передавал в соответствующий контролер. В данном случае **IngredientControler**.
Это позволило скрыть свойства репозиториев для других классов. И сделать один метод Save для всех, а так же не перегружать его.
А само свойство генерирует репозиторий при первом обращение и дальше хранит его.

2020-09-02 08:33 UTC, alex-geraschenko requested changes
1. Удаление `Task1` из этой ветки после мержа приведет к тому, что оно также удалиться и из мастера

2020-09-02 08:35 UTC, alex-geraschenko commented on Task2/Task2.BL/Interfaces/IRecipeRepository.cs
> +        public GenericRepository<List<Recipe>, Recipe> RecipesRepository { get; }
> Я переназвал интерфейс как IRecipeUnityOfWork

Видимо, вы не совсем разобрались с тем, что такое `Repository` и `UnitOfWork`

2020-09-02 08:35 UTC, alex-geraschenko commented on Task2/Task2.BL/Interfaces/ICategoryRepository.cs
> +        public GenericRepository<List<Category>, Category> CategoryRepository { get; }
> Я переназвал интерфейс как ICategoryUnityOfWork

Видимо, вы не совсем разобрались с тем, что такое `Repository` и `UnitOfWork`

2020-09-02 08:50 UTC, alex-geraschenko requested changes

2020-09-02 08:50 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/CategoryControler.cs
> +            _categoryUnityOfWork = categoryUnityOfWork;
Контроллер должен получать не `UnitOfWork`, а `Repository`, в котором внутри будет вызываться `UnitOfWork`

2020-09-02 08:50 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/IngredientControler.cs
> +            _ingredientUnityOfWork = ingredientUnityOfWork;
Контроллер должен получать не `UnitOfWork`, а `Repository`, в котором внутри будет вызываться `UnitOfWork`

2020-09-02 08:50 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/JSONManager.cs
> +            JsonSerializer serializer = new JsonSerializer();
Зачем создавать еще один `JsonSerializer`, если Вы уже один создали в конструкторе?

2020-09-02 08:50 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/RecipesControler.cs
> +            _recipeUnityOfWork = recipeUnityOfWork;
Контроллер должен получать не `UnitOfWork`, а `Repository`, в котором внутри будет вызываться `UnitOfWork`

2020-09-02 08:50 UTC, alex-geraschenko commented on Task2/Task2.BL/DAL/UnitOfWork.cs
> +        public void Save(UnitOfWork uow)
Вы и так находитесь в `UnitOfWork`. Зачем его еще раз передавать в качестве параметра?

2020-09-02 08:50 UTC, alex-geraschenko commented on Task2/Task2.BL/DAL/UnitOfWork.cs
> +            if (uow is ICategoryUnityOfWork)
Нарушение принципа **Open-Closed**

2020-09-02 08:50 UTC, alex-geraschenko commented on Task2/Task2.BL/Model/Category.cs
> +        public List<string> Subcategories { get; set;  }
Постарайтесь сделать структуру категорий плоскую, с использованием `ParentId`. https://stackoverflow.com/questions/9409021/id-parentid-list-to-hierarchical-list

2020-09-02 08:50 UTC, alex-geraschenko commented on Task2/Task2.BL/Model/Category.cs
> +        public static Category NewCategory(string Name)
Этот код лучше вынести в контроллер

2020-09-02 08:50 UTC, alex-geraschenko commented on Task2/Task2.BL/Model/Category.cs
> +        public bool FindSubcategory(string nameSubcategory)
Этот код лучше вынести в контроллер

2020-09-02 08:50 UTC, alex-geraschenko commented on Task2/Task2.BL/Model/Category.cs
> +        public void AddSubcategories(string NameSubcategories)
Этот код лучше вынести в контроллер

2020-09-02 08:50 UTC, alex-geraschenko commented on Task2/Task2.BL/Model/Recipe.cs
> +        public string Subcategory { get; }
Если реализуете плоскую структуру категорий, то в этом свойстве не будет необходимости

2020-09-07 15:13 UTC, Vakhaa commented on Task2/Task2.BL/Controler/CategoryControler.cs
> +            _categoryUnityOfWork = categoryUnityOfWork;
Извините, но не совсем понял. В статьях, что я нашёл, в контроллеры передавался класс UnityOf Work.
Статьи, которыми я пользовался:
> Microsoft: https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions/getting-started-with-ef-5-using-mvc-4/implementing-the-repository-and-unit-of-work-patterns-in-an-asp-net-mvc-application
>  Metanit: https://metanit.com/sharp/mvc5/23.3.php

2020-09-07 18:39 UTC, alex-geraschenko commented on Task2/Task2.BL/Controler/CategoryControler.cs
> +            _categoryUnityOfWork = categoryUnityOfWork;
ОК, пусть будет так. Когда будем работать с DI контейнерами, там будет удобнее передавать репозиторий

2020-09-07 18:41 UTC, alex-geraschenko approved these changes
Идея с использованием отдельных интерфейсов UnitOfWork для каждого контроллера, чтобы делать апкаст, так себе.
Но в целом хорошо, можно мержить

2020-09-07 20:48 UTC, merged