Task/task3
Vakhaa/altexsoft-lab-2020 pull request #4
Opened 2020-09-20 15:00 UTC by Vakhaa

2020-09-21 17:15 UTC, alex-geraschenko requested changes
В 3-м задании должны быть только SQL скрипты. Читайте внимательно задание

2020-09-22 18:11 UTC, Vakhaa commented
Упс, действительно не вчитался)

2020-09-22 19:14 UTC, alex-geraschenko requested changes
В пул реквесте должны быть только SQL скрипты.
Данный пул реквест после мержа удалит все файлы из `Task2`

2020-09-22 19:24 UTC, Vakhaa commented
А то что я переименовал все папки и файлы, я так понимаю не спасет Task2 от удаления ?

2020-09-22 19:26 UTC, closed without merging