Task/task3
Vakhaa/altexsoft-lab-2020 pull request #5
Opened 2020-09-22 20:06 UTC by Vakhaa

Сделал новую ветку и новый пулл реквест

2020-09-22 22:47 UTC, Vakhaa commented
Я не совсем понял, если делать ветку **orphan**, то гит не даёт делать пулл реквест, потому что история коммитов другая. А как тогда сделать ветку для мёржа в **master** без файлов и прочего ?

2020-09-23 16:37 UTC, alex-geraschenko commented
> Я не совсем понял, если делать ветку **orphan**, то гит не даёт делать пулл реквест, потому что история коммитов другая. А как тогда сделать ветку для мёржа в **master** без файлов и прочего (с других заданий)?

Новую ветку `tasks/task3` необходимо делать из `master`

2020-09-23 16:39 UTC, alex-geraschenko requested changes
1. Зачем Вам хранимые процедуры?
2. Категории и подкатегории должны быть в одной таблице. Я показывал это на вебинаре

2020-09-23 17:28 UTC, Vakhaa commented
Я добавил процедуры, что бы можно было компактно заполнять рецепты. Я решил создавать для рецептов таблицы, ингредиенты (что содержат в себе id ингредиентов и их количество в рецепте) и шаги приготовления. Я изначально подумал, что так проще хранить данные, потому что один рецепт может хранить список ингредиентов.

2020-09-23 17:47 UTC, Vakhaa commented
Если просто создать ветку с master - a, то там же будут файлы предыдущих заданий, так и должно быть ?

2020-09-24 08:13 UTC, alex-geraschenko commented
> Я добавил процедуры, что бы можно было компактно заполнять рецепты. Я решил создавать для рецептов таблицы, ингредиенты (что содержат в себе id ингредиентов и их количество в рецепте) и шаги приготовления. Я изначально подумал, что так проще хранить данные, потому что один рецепт может хранить список ингредиентов.

Задание звучало по другому. Без хранимых процедур, заполнение таблиц отдельными скриптами в правильной последовательности.

2020-09-24 08:16 UTC, alex-geraschenko commented
> Если просто создать ветку с master - a, то там же будут файлы предыдущих заданий, так и должно быть ?

Да, создать ветку из `master`. То, что там будут папки других заданий - нормально. Для этого задания тоже будет отдлеьная папка

2020-09-27 12:39 UTC, closed without merging