3 pull request
Vakhaa/altexsoft-lab-2020 pull request #6
Opened 2020-09-27 14:12 UTC by Vakhaa

2020-09-28 15:08 UTC, alex-geraschenko requested changes

2020-09-28 15:08 UTC, alex-geraschenko commented on Task3/schema/5.StepsInRecipe.sql
> +    [RecipeId]   INT   NOT NULL REFERENCES Recipes (Id),
Не хватает первичного ключа

2020-09-28 15:08 UTC, alex-geraschenko commented on Task3/schema/4.IngredientsInRecipe.sql
> +    [RecipeId]   INT   NOT NULL REFERENCES Recipes (Id),
Не хватает первичного ключа. В данном случае он должен быть составной (`RecipeId, IngredientId`)

2020-09-28 15:08 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +		INNER JOIN Categories AS c1 ON c.ParentId = c1.Id,
Запрос будет работать не правильно в случае, если у категорий больше одного уровня вложености.
Обратите внимание на **Common Table Expressions**

2020-09-29 14:50 UTC, alex-geraschenko requested changes

2020-09-29 14:50 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +FirstLayerCategories (Id, InheritorId, Name)AS
Не понимаю, зачем Вам понадобился еще один `CTE`?

2020-09-29 14:50 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +SELECT Recipes.Name As Recipe , Ingredients.Name As Ingredient, CountIngredient FROM
Запрос не выполняет поставленное условие задачи

2020-10-01 08:39 UTC, alex-geraschenko requested changes
Ваш запрос слишком переусложнен. Постарайтесь найти более простую запись

2020-10-01 08:39 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +        SELECT Recipes.Name As Recipe , Ingredients.Name As Ingredient, CountIngredient , DENSE_RANK() OVER(ORDER BY Recipes.Name ) AS Iterator FROM
Вместо `DENSE_RANK` лучше использовать `ROW_NUMBER` https://codingsight.com/similarities-and-differences-among-rank-dense_rank-and-row_number-functions/#:~:text=The%20only%20difference%20between%20RANK,used%20in%20ORDER%20BY%20Clause.&text=Finally%2C%20the%20ROW_NUMBER%20function%20has,number%20of%20the%20sorted%20records.

2020-10-01 08:39 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +		WHERE IR1.RecipeId = Recipes.Id AND c1.Id = 3 AND c1.LevelLayer<2
Зачем Вы ограничиваете уровень вложености категорий?

2020-10-01 08:39 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +		GROUP BY  Recipes.Name, Ingredients.Name , CountIngredient
Зачем Вам группировка?

2020-10-01 08:39 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +		Ingredients INNER JOIN IngredientsInRecipe AS IR1 ON IR1.IngredientId = Ingredients.Id
Какие в этом случае будут джоины?

2020-10-01 11:00 UTC, Vakhaa commented on Task3/queries/task.sql
> +		GROUP BY  Recipes.Name, Ingredients.Name , CountIngredient
В одном рецепте может быть разное количество ингредиентов,  для этого я вывожу : Название рецепта, ингредиент и количество данного ингредиента в рецепте.
Пример: 
> 1. Борщ, свекла, 1 шт
> 2. Борщ, соль, по вкусу
> 3. Борщ, бульон, 4 л.

2020-10-01 11:10 UTC, Vakhaa commented on Task3/queries/task.sql
> +		WHERE IR1.RecipeId = Recipes.Id AND c1.Id = 3 AND c1.LevelLayer<2
Что бы нельзя было отображать подкатегории подкатегорий и так дальше.  Оставив шаблон: Категории->Подкатегории-> Рецепты-> Рецепт.

2020-10-01 11:16 UTC, Vakhaa commented on Task3/queries/task.sql
> +        SELECT Recipes.Name As Recipe , Ingredients.Name As Ingredient, CountIngredient , DENSE_RANK() OVER(ORDER BY Recipes.Name ) AS Iterator FROM
Но если бы я использовал  ROW_NUMBER вместо DENSE_RANK и в WHERE поставил условие ROW_NUMBER<=3, то показало бы только первые три записи, а не три рецепта.

2020-10-01 11:21 UTC, Vakhaa commented on Task3/queries/task.sql
> +		Ingredients INNER JOIN IngredientsInRecipe AS IR1 ON IR1.IngredientId = Ingredients.Id
Не совсем понял вопрос, вернее совсем не понял. Но я переделал.

2020-10-01 11:22 UTC, Vakhaa commented on Task3/queries/task.sql
> +        SELECT Recipes.Name As Recipe , Ingredients.Name As Ingredient, CountIngredient , DENSE_RANK() OVER(ORDER BY Recipes.Name ) AS Iterator FROM
В одном рецепте может быть разное количество ингредиентов, для этого я вывожу : Название рецепта, ингредиент и количество данного ингредиента в рецепте.
Пример:

> Борщ, свекла, 1 шт
> Борщ, соль, по вкусу
> Борщ, бульон, 4 л.

2020-10-05 19:13 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +		WHERE IR1.RecipeId = Recipes.Id AND c1.Id = 3 AND c1.LevelLayer<2
Тогда теряется смысл подкатегорий. Вы можете вместо `LevelLayer` формировать строку из подкатегорий.

2020-10-05 19:18 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +		Ingredients INNER JOIN IngredientsInRecipe AS IR1 ON IR1.IngredientId = Ingredients.Id
Конкретно вот это место `... ON c.ParentId = c1.Id, Ingredients ...`

2020-10-05 19:21 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +        SELECT Recipes.Name As Recipe , Ingredients.Name As Ingredient, CountIngredient , DENSE_RANK() OVER(ORDER BY Recipes.Name ) AS Iterator FROM
> Но если бы я использовал ROW_NUMBER вместо DENSE_RANK и в WHERE поставил условие ROW_NUMBER<=3, то показало бы только первые три записи, а не три рецепта.

Зависит от того, как вы строите запрос. Во вложеном `SELECT` лучше выбирать только рецепты по категориям, а все сопутствующие данные (`Ingredients`, `IngredientsInRecipe`) джойнить уже на результат вложенного запроса

2020-10-05 20:43 UTC, Vakhaa commented
@alex-geraschenko ,  я переделал все выше перечисленное

2020-10-06 11:05 UTC, alex-geraschenko requested changes

2020-10-06 11:05 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +		WHERE c1.ParentId = 3
Условие `c1.ParentId = 3` будет работать только для первого уровня вложености. Его лучше перенести внутрь `CTE_Categories` вместо `WHERE ParentId IS NULL`

2020-10-06 11:05 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +) AS t ,Ingredients INNER JOIN IngredientsInRecipe AS IR1 ON IR1.IngredientId = Ingredients.Id
Мне все еще непонятна вот эта часть: `AS t ,Ingredients`. Как таблица `Ingredients` связывается с остальными частями запроса

2020-10-06 12:43 UTC, Vakhaa commented on Task3/queries/task.sql
> +) AS t ,Ingredients INNER JOIN IngredientsInRecipe AS IR1 ON IR1.IngredientId = Ingredients.Id
Таблица **IngredientsInRecipe** имеет связи многие ко многим. Эта таблица хранит id рецептов и ингредиентов, ну и количество  ингредиентов в рецепте. Я использую **INNER JOIN**, что бы вывести вместо id название ингредиента и их количество.

2020-10-06 16:43 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +) AS t ,Ingredients INNER JOIN IngredientsInRecipe AS IR1 ON IR1.IngredientId = Ingredients.Id
**INNER JOIN** Вы используете только между `Ingredients` и `IngredientsInRecipe`

2020-10-08 08:27 UTC, alex-geraschenko requested changes

2020-10-08 08:27 UTC, alex-geraschenko commented on Task3/queries/task.sql
> +) AS t, Ingredients as I, IngredientsInRecipe AS IR1
Вместо того, чтобы удалять INNER JOIN для `IngredientsInRecipe` нужно было добавить INNER JOIN для `Ingredients`

2020-10-08 08:53 UTC, Vakhaa commented on Task3/queries/task.sql
> +) AS t, Ingredients as I, IngredientsInRecipe AS IR1
угу, теперь понял

2020-10-08 09:25 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-10-08 09:30 UTC, merged