Task/task4
Vakhaa/altexsoft-lab-2020 pull request #8
Opened 2020-10-07 20:14 UTC by Vakhaa

У меня еще не сдано 3 задание

2020-10-07 20:55 UTC, serhii-shkodenko requested changes
Файлов из третьего задания в пулл реквесте для четвертого быть не должно.

2020-10-07 20:55 UTC, serhii-shkodenko commented on Task4/HomeTask4.Cmd/Program.cs
> +            var categoryController = new CategoryController(unitOfWork);
Создание контроллеров тоже возложите на IoC контейнер.

2020-10-07 20:55 UTC, serhii-shkodenko commented on Task4/HomeTask4.Cmd/Program.cs
> +/// </summary>
Этот комментрий был оставлен для Вас в примере задания. Его можно удалить, если Вы с ним ознакомились.

2020-10-07 20:55 UTC, serhii-shkodenko commented on Task4/HomeTask4.Cmd/Program.cs
> +        /// <returns><see cref="IHostBuilder" /> hostBuilder</returns>
Если создаете Xml комментарии для создания документации, то заполняйте их полностью, не оставляйте пустыми.

2020-10-07 20:55 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +        public Category CurrentCategories { get; set; }
Свойство называется в множественном числе, а наименование его типа - существительное в единственном числе. Поправьте.

2020-10-07 20:55 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +        /// <param name="categoryRepository">Репозиторий категории.</param>
Конструктор поменяли, а комментарии забыли.

2020-10-07 20:55 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +            return _unitOfWork.Repository.ListAsync<Category>().Result.Where(c => c.ParentId == null).ToList();
1. Переделайте все методы во всех контроллерах на асинхронные. 
2. Избегайте использования `Task.Result`. Почему [стоит почитать здесь](https://stackoverflow.com/questions/27464287/what-is-the-difference-between-await-taskt-and-taskt-result).

2020-10-07 20:55 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +            CurrentCategories = GetCategories().First(c => c.Id == idCategory);
Код упадет с исключением, если категория не будет найдена. Используйте `FirstOrDefault()`.

2020-10-07 20:55 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +        public bool WalkCategories(string str = "")
Привычнее будет использовать для дефолтных значений `null` или `string.Empty`.

2020-10-07 20:55 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +        /// </summary>
Комментарии следует добавлять в код, если они несут какую-то нагрузку полезную. В этом комментарии я ее не вижу.

2020-10-07 20:55 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +        private IUnitOfWork _unitOfWork;
`IUnitOfWork` это не репозиторий.

2020-10-07 20:55 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +            temp.Wait();
Здесь Вы блокируете поток. Не делайте так. Везде удалите. Переделайте методы в контроллерах на асинхронные.

2020-10-07 21:24 UTC, Vakhaa commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +        private IUnitOfWork _unitOfWork;
Это старый комментарий, забыл поправить)

2020-10-10 13:05 UTC, Vakhaa commented
Файлы 3 задания есть в пулл реквеста 4, потому что я открыл пулл реквест 4 задания до того как смержил 3 задание с мастером. Мне лучше пересоздать пулл реквест ?

2020-10-13 20:36 UTC, serhii-shkodenko commented
> Файлы 3 задания есть в пулл реквеста 4, потому что я открыл пулл реквест 4 задания до того как смержил 3 задание с мастером. Мне лучше пересоздать пулл реквест ?

Пересоздавать не нужно. По-большому счету, третье и четвертое задание можно было выполнять паралельно. Ветку для четвертого задания Вы могли бранчевать хоть от мастера, хоть от ветки с третьим. Подозреваю, что Вы каким-то образом скопировали файлы из третьего задания в ветку для четвертого. Этого делать не нужно было.

1. Удалите файлы третьего задания из `taks4`, предварительно убедившись (!!!), что они останутся в ветке `task3`. 
2. В ветке `taks4` создайте коммит после удаления. 
3. Запушьте изменения на ремоут для `taks4`.

2020-10-13 20:38 UTC, Vakhaa commented
В этот раз я именно бранчивал от 3 задания. Так что история комиитов должна быть одна.

2020-10-13 20:46 UTC, Vakhaa commented
Как я понимаю, если я удалю сейчас файлы 3 таска, то при слиянии 4 ветки с мастером оно удалит 3 таск с последнего, так как это тот же самый таск. Или я путаю ?

2020-10-13 20:47 UTC, Vakhaa commented
В этот раз я именно бранчивал от 3 задания. Так что история комиитов должна быть одна. Как я понимаю, если я удалю сейчас файлы 3 таска, то при слиянии 4 ветки с мастером оно удалит 3 таск с последнего, так как это тот же самый таск. Или я путаю ?

> > Файлы 3 задания есть в пулл реквеста 4, потому что я открыл пулл реквест 4 задания до того как смержил 3 задание с мастером. Мне лучше пересоздать пулл реквест ?
> 
> Пересоздавать не нужно. По-большому счету, третье и четвертое задание можно было выполнять паралельно. Ветку для четвертого задания Вы могли бранчевать хоть от мастера, хоть от ветки с третьим. Подозреваю, что Вы каким-то образом скопировали файлы из третьего задания в ветку для четвертого. Этого делать не нужно было.
> 
> 1. Удалите файлы третьего задания из `taks4`, предварительно убедившись (!!!), что они останутся в ветке `task3`.
> 2. В ветке `taks4` создайте коммит после удаления.
> 3. Запушьте изменения на ремоут для `taks4`.

2020-10-13 21:09 UTC, serhii-shkodenko commented
> В этот раз я именно бранчивал от 3 задания. Так что история комиитов должна быть одна. Как я понимаю, если я удалю сейчас файлы 3 таска, то при слиянии 4 ветки с мастером оно удалит 3 таск с последнего, так как это тот же самый таск. Или я путаю ?
> 
> > > Файлы 3 задания есть в пулл реквеста 4, потому что я открыл пулл реквест 4 задания до того как смержил 3 задание с мастером. Мне лучше пересоздать пулл реквест ?
> > 
> > 
> > Пересоздавать не нужно. По-большому счету, третье и четвертое задание можно было выполнять паралельно. Ветку для четвертого задания Вы могли бранчевать хоть от мастера, хоть от ветки с третьим. Подозреваю, что Вы каким-то образом скопировали файлы из третьего задания в ветку для четвертого. Этого делать не нужно было.
> > 
> > 1. Удалите файлы третьего задания из `taks4`, предварительно убедившись (!!!), что они останутся в ветке `task3`.
> > 2. В ветке `taks4` создайте коммит после удаления.
> > 3. Запушьте изменения на ремоут для `taks4`.

Да, Вы правы, удаление файлов `task3` в ветке `taks4` приведет к удалению файлов в мастере после мержа. Это произойдет потому, что Вы по зачем-то вмержили `task3` в `taks4`.

2020-10-13 22:04 UTC, serhii-shkodenko requested changes

2020-10-13 22:04 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +            return await Task.Run(()=>_unitOfWork.Repository.ListAsync<Category>().GetAwaiter().GetResult().Where(c => c.ParentId == null).ToList());
Для подобных методов имеет смысл удалить `await`, следующий перед return. Таким образом, компилятор не будет разворачивать машину состояний, а вернет таску, выполнение которой Вы подождете выше по стеку вызовов. Пожалуйста, просмотрите Весь код и поправьте все подобные методы.

2020-10-13 22:04 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +            return await Task.Run(()=>_unitOfWork.Repository.ListAsync<Category>().GetAwaiter().GetResult().Where(c => c.ParentId == null).ToList());
Я не вижу причин создавать асинхронную обертку над этим синхронным кодом (в который Вы преобразовали асинхронный код). [Больше можно прочитать здесь](https://devblogs.microsoft.com/pfxteam/should-i-expose-asynchronous-wrappers-for-synchronous-methods/). Пройдитесь по коду и поправьте в других местах. Везде удалите, пожалуйста `Task.Run()`.

2020-10-13 22:04 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +            return GetCategoriesAsync().GetAwaiter().GetResult().FirstOrDefault(i => i.Name == nameCategory);
Разберитесь, что делает Ваш метод и что он должен возвращать.

2020-10-13 22:04 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +            return GetCategoriesAsync().GetAwaiter().GetResult().FirstOrDefault(i => i.Name == nameCategory);
Использование `GetAwaiter().GetResult()` ведет у появлению deadlock'ов. Несмотря на то, что в ASP.NET Core отсутствует `SynchronizationContext` и, следовательно, `await` его не захватывает, этот код блокирует поток. То есть вместо того, чтобы заниматься какими-то другими вещами, он синхронно будет ждать завершения выполнения метода `GetCategoriesAsync()`. Пожалуйста, пройдитесь по всему коду и поправьте.

2020-10-13 22:04 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +            GetIngredientsAsync();
Вы не ждете завершения метода. Это плохо, потому что Вы не отловите исключение. Поправьте, не применяя `GetAwaiter().GetResult()`.

2020-10-13 22:04 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +        public void AddRecipe(string nameRecipe, int subcategoriesId, string description, List<int> ingredientsId, List<string> countIngred, List<string> stepsHowCooking)
Роберт Мартин в своей книге "Чистый код" призывает писать методы только с несколькими параметрами (одним, двумя или тремя). У Вас шесть параметров. Возможно, Вам стоит объединить эти данные в рамках какой-то сущности. Назание метода наталкивает на мысль, что параметром должен быть рецепт.

2020-10-13 22:04 UTC, serhii-shkodenko commented on Task4/HomeTask4.Core/Entities/Ingredient.cs
> +        /// Конструктор.
Комментарии должны быть полезны для тех, кто их читает. То, что это конструктор, не несет никакой информации, удалите.

2020-10-13 22:04 UTC, serhii-shkodenko commented on Task4/HomeTask4.Infrastructure/Data/Config/CategoryConfig.cs
> +            /*builder.HasMany(p => p.Subcategory)
Всегда удаляйте из пулл реквеста закомментированный код.

2020-10-13 22:06 UTC, Vakhaa commented
> > В этот раз я именно бранчивал от 3 задания. Так что история комиитов должна быть одна. Как я понимаю, если я удалю сейчас файлы 3 таска, то при слиянии 4 ветки с мастером оно удалит 3 таск с последнего, так как это тот же самый таск. Или я путаю ?
> > > > Файлы 3 задания есть в пулл реквеста 4, потому что я открыл пулл реквест 4 задания до того как смержил 3 задание с мастером. Мне лучше пересоздать пулл реквест ?
> > > 
> > > 
> > > Пересоздавать не нужно. По-большому счету, третье и четвертое задание можно было выполнять паралельно. Ветку для четвертого задания Вы могли бранчевать хоть от мастера, хоть от ветки с третьим. Подозреваю, что Вы каким-то образом скопировали файлы из третьего задания в ветку для четвертого. Этого делать не нужно было.
> > > 
> > > 1. Удалите файлы третьего задания из `taks4`, предварительно убедившись (!!!), что они останутся в ветке `task3`.
> > > 2. В ветке `taks4` создайте коммит после удаления.
> > > 3. Запушьте изменения на ремоут для `taks4`.
> 
> Да, Вы правы, удаление файлов `task3` в ветке `taks4` приведет к удалению файлов в мастере после мержа. Это произойдет потому, что Вы по зачем-то вмержили `task3` в `taks4`.

Да, я после создания `task4` добавлял коммиты в `task3`. Я подумал, что при мерже `task4` с `master` приведет к конфликту, так как файлы `task3` в ветке `task4` были более старые. Я так понял, что не стоило мержить после с task3 в task4.

А то что файлы `task3` в `task4` сейчас одинаковы с `master`-ом, разве оно не должно просто слиться без ошибок ?

2020-10-13 22:12 UTC, serhii-shkodenko commented
> > > В этот раз я именно бранчивал от 3 задания. Так что история комиитов должна быть одна. Как я понимаю, если я удалю сейчас файлы 3 таска, то при слиянии 4 ветки с мастером оно удалит 3 таск с последнего, так как это тот же самый таск. Или я путаю ?
> > > > > Файлы 3 задания есть в пулл реквеста 4, потому что я открыл пулл реквест 4 задания до того как смержил 3 задание с мастером. Мне лучше пересоздать пулл реквест ?
> > > > 
> > > > 
> > > > Пересоздавать не нужно. По-большому счету, третье и четвертое задание можно было выполнять паралельно. Ветку для четвертого задания Вы могли бранчевать хоть от мастера, хоть от ветки с третьим. Подозреваю, что Вы каким-то образом скопировали файлы из третьего задания в ветку для четвертого. Этого делать не нужно было.
> > > > 
> > > > 1. Удалите файлы третьего задания из `taks4`, предварительно убедившись (!!!), что они останутся в ветке `task3`.
> > > > 2. В ветке `taks4` создайте коммит после удаления.
> > > > 3. Запушьте изменения на ремоут для `taks4`.
> > 
> > 
> > Да, Вы правы, удаление файлов `task3` в ветке `taks4` приведет к удалению файлов в мастере после мержа. Это произойдет потому, что Вы по зачем-то вмержили `task3` в `taks4`.
> 
> Да, я после создания `task4` добавлял коммиты в `task3`. Я подумал, что при мерже `task4` с `master` приведет к конфликту, так как файлы `task3` в ветке `task4` были более старые. Я так понял, что не стоило мержить после с task3 в task4.
> 
> А то что файлы `task3` в `task4` сейчас одинаковы с `master`-ом, разве оно не должно просто слиться без ошибок ?

Да, смержится без ошибок. То что Вы вмержили третью таску в четвертую нарушило предназначение ветвления - возможность независимой разработки.

2020-10-13 22:16 UTC, Vakhaa commented
Ясненько, боялся конфликтов при мерже. Впредь буду за этим следить.

2020-10-14 11:27 UTC, Vakhaa commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +        public void AddRecipe(string nameRecipe, int subcategoriesId, string description, List<int> ingredientsId, List<string> countIngred, List<string> stepsHowCooking)
Я вчера, когда писал тесты столкнулся с тем, что  было сложновато написать тест под этот метод. И действительно его нужно разбить на три части.  Уже сделал.

2020-10-21 12:01 UTC, alex-geraschenko requested changes

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/UnitOfWork.cs
> +                    _repository = new Repository(_context);
Лучше использовать **Dependency Injection** в контроллере

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/Repository.cs
> +            return await Task.Run(()=> _context.Set<T>().OrderBy(i => i.Id).ToList());
Вместо `Task.Run` лучше использовать `ToListAsync`

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/Repository.cs
> +            return await Task.Run(() => _context.Set<T>().FirstOrDefault( item => item.Id == id));
Вместо `Task.Run` лучше использовать `FirstOrDefaultAsync`

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/Repository.cs
> +            await Task.Run(() => _context.Set<T>().Add(entity));
Не стоит использовать `Task.Run` без необходимости.
Лучше использовать `Task.FromResult` при возврате из метода

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/Config/StepsInRecipeConfig.cs
> +
Удалите лишние пробелы

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/Repository.cs
> +
Удалите лишние пробелы

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/Config/RecipeConfig.cs
> +
Удалите лишние пробелы

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/Config/CategoryConfig.cs
> +
Удалите лишние пробелы

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Entities/IngredientsInRecipe.cs
> +        private int  Id {get;}
Зачем это свойство?

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Entities/Category.cs
> +        public Category() { }
Не хватает двух свойств: 
```
public Category Parent { get; set; }
public IEnumerable<Category> Children { get; set; }
```

В этом случае отпадет необходимость в `SubcategoryController`

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +            return GetRecipesAsync().GetAwaiter().GetResult().FirstOrDefault(r => r.Id == recipesId);
Вместо `GetAwaiter().GetResult()` используйте `async/await`

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +            var getRecipes = await GetRecipesAsync();
Имя переменной не соответствует ее содержанию

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +            await _unitOfWork.Repository.ListAsync<IngredientsInRecipe>();
Почему вызовы происходят без присвоения результата?

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +            var getIngredients = await GetIngredientsAsync();
Имя переменной не соответствует содержанию

2020-10-21 12:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +            return _unitOfWork.Repository.ListAsync<Category>().GetAwaiter().GetResult().Where(c => c.ParentId == null).ToList();
Вместо `GetAwater().GetResult()` используйте `async/await`

2020-10-21 12:31 UTC, Vakhaa commented on Task4/HomeTask4.Core/Entities/IngredientsInRecipe.cs
> +        private int  Id {get;}
Это свойство скрывает Id, который класс наследует от BaseEntity. Я умышленно пошел на это преступление, что бы не переписывать  repository и так далее. IngredientsInRecipe не имеет поля Id в бд, вместо идентификатора у него составной ключ.

2020-10-21 12:50 UTC, Vakhaa commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +            await _unitOfWork.Repository.ListAsync<IngredientsInRecipe>();
При загрузки рецепта IngredientsInRecipe и StepsInRecipe сами мапятся к рецепту через навигационные свойства (если я правильно использую термины). Только перед этим, эти два компонента должны быть инициализированы. Я решил это делать уже имеющимся инструментом.

2020-10-21 13:01 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +            await _unitOfWork.Repository.ListAsync<IngredientsInRecipe>();
Для этого существует специальный механизм `Include` https://docs.microsoft.com/en-us/ef/core/querying/related-data/

2020-10-21 13:02 UTC, Vakhaa commented on Task4/HomeTask4.Core/Entities/Category.cs
> +        public Category() { }
Я не хотел изначально смешивать логику категорий и подкатегорий.

2020-10-21 13:43 UTC, Vakhaa commented on Task4/HomeTask4.Core/Entities/Category.cs
> +        public Category() { }
Мне действительно лучше смешать два контроллера ?

2020-10-21 15:07 UTC, alex-geraschenko requested changes
1. Пройдите по всему коду и исправьте `GetAwaiter().GetResult()` на `async/await`
2. Пройдите по всему коду и исправьте имена переменных, которые у Вас начинаются с `get`. Например, вместо `getCategory` должно быть `categories`

2020-10-21 15:07 UTC, alex-geraschenko commented on Task4/HomeTask4.Cmd/Program.cs
> +                                await unitOfWork.SaveChangesAsync();
Сохранять данные на выходе из приложения плохая идея. Если приложение по какой-то причине упадет, то все данные потеряются

2020-10-21 15:07 UTC, alex-geraschenko commented on Task4/HomeTask4.Cmd/Program.cs
> +                            await recipeController.SaveAsync();
Сохранение должно происходить внутри методов контроллера, а не вызываться отдельно снаружи. Вся логика создания рецепта, включая добавление ингридиентов и шагов, а также сохранение в базу должно быть внутри контроллера.

2020-10-21 15:07 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +        public async Task SaveAsync()
Этот метод не нужен. Сохранение должно происходить внутри метода добавления или изменения

2020-10-21 15:07 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +        public async Task SaveAsync()
Этот метод не нужен. Сохранение должно происходить внутри метода добавления или изменения

2020-10-21 15:07 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +        public async Task SaveAsync()
Этот метод не нужен. Сохранение должно происходить внутри метода добавления или изменения

2020-10-21 15:07 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +                await SaveAsync();
Вызывать сохранение в цикле плохая идея.

2020-10-21 15:07 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +                await SaveAsync();
Вызывать сохранение в цикле плохая идея

2020-10-21 15:07 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/SubcategoryController.cs
> +    public class SubcategoryController
В этом контроллере нет неоходимости. Добавьте навигационные свойства `Parent` и `Children` в `Сategory` и загружайте их через `Include`

2020-10-21 15:07 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/EFRepository.cs
> +        public async Task SaveAsync()
Этот метод не нужен. Сохранение должно вызываться на уровне `UnitOfWork` или внутри методов добавления, изменения или удаления

2020-10-21 15:07 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/UnitOfWork.cs
> +            get
Этот код можно упростить до автосвойста и избавиться от приватного поля `_repository`

2020-10-21 15:36 UTC, Vakhaa commented on Task4/HomeTask4.Cmd/Program.cs
> +                                await unitOfWork.SaveChangesAsync();
Это на всякий случай) Сейчас уберу.

2020-10-21 16:22 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Entities/IngredientsInRecipe.cs
> +        private int  Id {get;}
При конфигурировании сущностей свойство `Id` можно проигнорировать:
```
public void Configure(EntityTypeBuilder<IngredientsInRecipe> builder)
{
    builder.Ignore("Id");
    builder.HasKey(x => new { x.RecipeId,x.IngredientId });
}
```

2020-10-21 16:22 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Entities/Category.cs
> +        public Category() { }
Тут нет смешивания логики

2020-10-21 17:40 UTC, alex-geraschenko requested changes

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.SharedKernel/Interfaces/IRepository.cs
> +        Task SaveAsync();
Этот метод должен быть в `UnitOfWork`

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.SharedKernel/Interfaces/IUnitOfWork.cs
> +        IRepository Repository{ get; }
Не хватает метода сохранения

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/EFRepository.cs
> +            if(typeof(T) == typeof(Recipe))
Этот метод нарушает принцип **Open-Closed**

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/EFRepository.cs
> +            var result = await Task.FromResult(_context.Set<T>().Add(entity).Entity);
Не надо использовать `Task` где попало. В данном методе это абсолютно излишне.

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/EFRepository.cs
> +            await Task.Run(()=> _context.Set<T>().Remove(entity));
Не надо использовать `Task` где попало. В данном методе это абсолютно излишне. Лучше сделать мето синхронным

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/EFRepository.cs
> +            await Task.Run(()=> _context.Set<T>().Update(entity));
Не надо использовать `Task` где попало. В данном методе это абсолютно излишне. Лучше сделать мето синхронным

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/EFRepository.cs
> +            if(typeof(T) == typeof(Recipe))
Вы не разобрались до конца, как использовать `Include`

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/Config/CategoryConfig.cs
> +            builder.Property(s => s.Id).HasColumnName("Id");
Не хватает конфигурации навигационных свойств

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Cmd/Program.cs
> +            var unitOfWork = host.Services.GetRequiredService<IUnitOfWork>();
Переменная `unitOfWork` нигде не используется. Ее надо удалить

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Cmd/Program.cs
> +                            Console.WriteLine(++count + ". " + category.Name);
Вы по разному выводите информацию. Где-то конкатенация строк, где-то интерполяция. Пройдите по всему коду и исправьте единообразно. Лучше всего использовать интерполяцию.

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Cmd/Program.cs
> +                            Console.WriteLine(++count + ". " + category.Name);
Вместо счетчика лучше выводить `Id` категории, как Вы это делаете для рецептов. Поменяйти по всему классу

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Cmd/Program.cs
> +                        #region Walk into categories
Выделите код из каждого кейса в отдельный метод, чтобы улучшить читаемость кода

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Cmd/Program.cs
> +                        case 1:
Выделите код из каждого кейса в отдельный метод, чтобы улучшить читаемость кода

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Cmd/Program.cs
> +                                if (int.TryParse(Console.ReadLine(), out count))
Это условие и `while` можно совместить

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Cmd/Program.cs
> +                                if (int.TryParse(Console.ReadLine(), out countSteps))
Это условие и `while` можно совместить

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/CategoryController.cs
> +        public Category CurrentSubcategory { get; set; }
Любая подкатегория - это абсолютно такая же категория, как любая категория верхнего уровня. Поэтому пересмотрите логику работы с категориями как с деревом, а не как с отдельными видами сущностей

2020-10-21 17:40 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +            if (ingredients.Any(ingr => ingr.Name.ToLower() == nameIngredient.ToLower()))
Эту логику можно упростить. Если Вы вызываете `FirstOrDefault`, то предварительно проверь наличие не нужно.

2020-10-21 17:47 UTC, Vakhaa commented on Task4/HomeTask4.Cmd/Program.cs
> +                            Console.WriteLine(++count + ". " + category.Name);
Но если вместо счетчика добавить id, то последовательность не будет : n+1. Так как можно добавить категорию после подкатегории и вывод будет : 

> 1. Первые блюда.
> 2. Вторые блюда.
> 10. Десерты.

2020-10-21 17:56 UTC, alex-geraschenko commented on Task4/HomeTask4.Cmd/Program.cs
> +                            Console.WriteLine(++count + ". " + category.Name);
Работайте с категориями не как с плоской структурой, а как с деревом. И последовательность Вам не нужна. Вам нужно знать id, чтобы была возможность в любой момент перейти внутрь категории и отобразить ее подкатегории

2020-10-27 17:22 UTC, alex-geraschenko requested changes

2020-10-27 17:22 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/EFRepository.cs
> +            await _context.Set<IngredientsInRecipe>().Include(i => i.Recipe).ThenInclude(r => r.Ingredients)
Этот метод абсолютно неэффективно.
1. Нет возможности фильтровать на уровне базы, а значит все время приходится вытаскивать все записи и уже в памяти фильтровать. Пока в базе данных не много, то это не проблема. Но как только количество записей перевалит за 1000, то это уже будет ощутимая просадка по производительности.
2. Загружать из базы постоянно сущности, которые Вам в данный момент не нужны, тоже не добаляют производительности, а еще больше ее усугубляют.

Изучите подробнее тут https://metanit.com/sharp/entityframework/3.13.php , как лучше реализовать фильтрацию и подгрузку навигационных свойств

2020-10-28 10:55 UTC, alex-geraschenko requested changes
Вы невнимательно читаете комментарии. Я Вам говорил, что не реализована фильтрация на уровне базы, а Вы вместо этого прикрутили _Lazy Loading_. Хотя в той статье, на которую я оставлял ссылку есть пример, как обойтись без _Lazy Loading_.

2020-10-30 19:40 UTC, alex-geraschenko requested changes
1. Почему методы обращения к базе данных стали синхронными?
2. Вы добавили методы для фильтрации на уровне базы данных, но ими не воспользовались. Вся фильтрация все еще происходит в памяти

2020-11-05 17:41 UTC, alex-geraschenko requested changes

2020-11-05 17:41 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +                var result = await _unitOfWork.Repository.GetByNameAsync<Ingredient>(i => i.Name.ToLower() == answer.ToLower(), i => i.IngredientsInRecipe);
Здесь Вы делаете вызов к базе данных 2 раза: 1 раз для проверки существования, а 2 раз для чтения этих данных. В данном случае дополнительная проверка избыточна, достаточно сделать запрос на получение данных, и проверить результат на `null`.
Кроме того, если вы называете метод `GetByName`, то нет смысла передавать первым параметром выражение `i => i.Name.ToLower() == answer.ToLower()`. Происходит тавтология. В этом случае лучше передавать или параметр `answer` или изменить имя метода на более обобщенное.

2020-11-05 17:41 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +                .IsExistsAsync<Ingredient>(i => i.Name.ToLower() == nameIngredient.ToLower(), i => i.IngredientsInRecipe))
Здесь Вы делаете вызов к базе данных 2 раза: 1 раз для проверки существования, а 2 раз для чтения этих данных. В данном случае дополнительная проверка избыточна, достаточно сделать запрос на получение данных, и проверить результат на `null`.

2020-11-05 17:41 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +            return _unitOfWork.Repository.GetByIdAsync<Ingredient>(i => i.Id == ingredientId, i=>i.IngredientsInRecipe);
Если вы называете метод `GetById`, то нет смысла передавать первым параметром выражение `i => i.Id == ingredientId`. Происходит тавтология. В этом случае лучше передавать или параметр `ingredientId` или изменить имя метода на более обобщенное.

2020-11-05 17:41 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +                .IsExistsAsync<Recipe>(x=>x.Name == nameRecipe, x => x.Category, x => x.StepsHowCooking, x => x.IngredientsInRecipe))
Здесь Вы делаете вызов к базе данных 2 раза: 1 раз для проверки существования, а 2 раз для чтения этих данных. В данном случае дополнительная проверка избыточна, достаточно сделать запрос на получение данных, и проверить результат на `null`.

2020-11-05 17:41 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +            return _unitOfWork.Repository.GetByIdAsync<Recipe>(r => r.Id == recipesId,r=>r.Category,r=>r.StepsHowCooking,r=>r.IngredientsInRecipe);
Если вы называете метод `GetById`, то нет смысла передавать первым параметром выражение `i => i.Id == recipesId`. Происходит тавтология. В этом случае лучше передавать или параметр `recipesId` или изменить имя метода на более обобщенное.

2020-11-05 17:41 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +                await _unitOfWork.Repository.AddAsync(new IngredientsInRecipe(CurrentRecipe.Id, ingredientsId[steps], countIngred[steps]));
Постарайтесь избегать обращений к базе данных в цикле. Это сильно ухудшает производительность. В этом случае лучше в цикле добавлять сущности в репозиторий без сохранения, а сохранять уже после завершения цикла

2020-11-05 17:41 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +                await _unitOfWork.Repository.AddAsync(new StepsInRecipe(CurrentRecipe.Id, steps));
Постарайтесь избегать обращений к базе данных в цикле. Это сильно ухудшает производительность. В этом случае лучше в цикле добавлять сущности в репозиторий без сохранения, а сохранять уже после завершения цикла

2020-11-05 17:41 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/EFRepository.cs
> +            return Include(predicate, includeProperties).FirstOrDefault();
Методы `GetByIdAsync` и `GetByNameAsync` дублируют друг друга. Лучше сделать их обобщенным

2020-11-05 17:41 UTC, alex-geraschenko commented on Task4/HomeTask4.Infrastructure/Data/EFRepository.cs
> +                    .Aggregate(query, (current, includeProperty) => current.Include(includeProperty))
В этом методе дублирование кода

2020-11-10 12:36 UTC, alex-geraschenko requested changes

2020-11-10 12:36 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/IngredientController.cs
> +            var result = await _unitOfWork.Repository.GetWithIncludeEntityAsync<Ingredient>(i => i.Name.ToLower() == answer.ToLower(), i => i.IngredientsInRecipe);
Дублирование кода с методом `FindAndGetIngredientAsync`

2020-11-10 16:49 UTC, alex-geraschenko requested changes

2020-11-10 16:49 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +        public async Task AddedStepsInRecipeAsync(List<string> stepsHowCooking, List<StepsInRecipe> stepsInRecipe =null)
Зачем нужен `stepsInRecipe` как параметр, если он всегда переопределяется внутри метода?

2020-11-10 16:49 UTC, alex-geraschenko commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +        public async Task AddedIngredientsInRecipeAsync(List<int> ingredientsId, List<string> countIngred, List<IngredientsInRecipe> ingredientsInRecips = null)
Зачем нужен `ingredientsInRecips` как параметр, если он всегда переопределяется внутри метода ?

2020-11-10 17:27 UTC, Vakhaa commented on Task4/HomeTask4.Core/Controllers/RecipeController.cs
> +        public async Task AddedStepsInRecipeAsync(List<string> stepsHowCooking, List<StepsInRecipe> stepsInRecipe =null)
Я на автомате сделал, так как в смежных ситуациях меня раньше просили убирать переменные в параметры метода. Сейчас переделаю.

2020-11-10 18:04 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-11-10 19:24 UTC, merged