Added Tests for Core
Vakhaa/altexsoft-lab-2020 pull request #9
Opened 2020-11-12 02:01 UTC by Vakhaa

2020-11-12 12:10 UTC, serhii-shkodenko requested changes
Пожалуйста, вынесите создание общих для всех тестов моков в конструкторы.

2020-11-12 12:10 UTC, serhii-shkodenko commented on Task4/XUnitTest/Controllers/CategoryControllerTest.cs
> +            var repositoryMock = new Mock<IRepository>(); // Create mock object for IRepository
Вы в каждом тесте создаете этот объект, а также `unitOfWorkMock`, свойству которому присваиваете `repositoryMock`. Вы также в каждом тесте создаете `controller`. Этого можно избежать, если в классе создать приватные поля, которые инициализировать в конструкторе. Поскольку в xUnit конструктор класса с тестами вызывается для каждого теста, тесты будут проходить  в изолированном контексте.

2020-11-12 12:10 UTC, serhii-shkodenko commented on Task4/XUnitTest/Controllers/CategoryControllerTest.cs
> +            unitOfWorkMock.Setup(o => o.Repository)
Для настройки ожиданий для свойств в Moq есть `SetupGet()`. Используйте его.

2020-11-12 12:10 UTC, serhii-shkodenko commented on Task4/XUnitTest/Controllers/CategoryControllerTest.cs
> +            var name = Guid.NewGuid().ToString();
Генерация строковых значений, используя методы класса Guid это распространенный приём, однако здесь он избыточен. Ниже объяснил почему.

2020-11-12 12:10 UTC, serhii-shkodenko commented on Task4/XUnitTest/Controllers/CategoryControllerTest.cs
> +            Assert.Equal(2, entities.Count());
Давайте разберемся, что делает Ваше тестируемый метод, и что нам надо протестировать. Вот код метода: 
```
public Task<IEnumerable<Category>> GetCategoriesAsync()
{
    return _unitOfWork.Repository.GetWithIncludeListAsync<Category>(c => c.ParentId == null,c=>c.Children);
}
```
Тестируемый метод можно назвать оберткой над методом репозитория и возвращает потребителю то, что вернет `GetWithIncludeListAsync()`. Поэтому, как мне представляется, здесь будет достаточно настроить возвращаемое значение для `GetWithIncludeListAsync()` и проверить, что оно без каких либо изменений было передано "наверх". Таким образом Ваш тест можно сократить до:
![test_simplify](https://user-images.githubusercontent.com/69808191/98938455-97a73200-24f0-11eb-801c-e7e8a888f76f.png)

2020-11-12 12:30 UTC, serhii-shkodenko requested changes

2020-11-12 12:30 UTC, serhii-shkodenko commented on Task4/XUnitTest/Controllers/CategoryControllerTest.cs
> +        public async void GetCategories()
Обратите внимание на имена методов. Вы можете [выбрать одну из этих конвенций](https://dzone.com/articles/7-popular-unit-test-naming) и далее ей следовать по всему проекту.

2020-11-12 12:30 UTC, serhii-shkodenko commented on Task4/XUnitTest/Controllers/CategoryControllerTest.cs
> +        public async void GetCategories()
Не пишите `async void` методов. [Почему это плохая практика](https://www.google.com/search?q=async+void+why+it+is+bad&oq=async+void+why+it+is+bad).

2020-11-16 10:34 UTC, serhii-shkodenko requested changes

2020-11-16 10:34 UTC, serhii-shkodenko commented on Task4/XUnitTest/Controllers/CategoryControllerTest.cs
> +        List<Category> _expectedListCategory;
Добавьте для всех полей `readonly` модификаторы.

2020-11-16 10:34 UTC, serhii-shkodenko commented on Task4/HomeTask4.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "XUnitTest", "XUnitTest\XUnitTest.csproj", "{BEAC6BD6-1CB7-4305-85EA-014D50BEEF77}"
Достаточно распространенной конвенцией для именования проектов с юнит тестами является следующая:

- Company.Website - the project
- Company.Website.Tests
Переименуйте в соответствии с ней свой проект.

2020-11-16 10:34 UTC, serhii-shkodenko commented on Task4/XUnitTest/Controllers/CategoryControllerTest.cs
> +        }
Добавьте еще тесты для случаев, когда `int.TryParse` возвращает `false`, а также когда `CurrentCategory == null`.

2020-11-16 16:12 UTC, serhii-shkodenko commented
Отметьте, пожалуйста, с помощью кнопки "Resolve conversation" исправленные комментарии.

2020-11-16 16:13 UTC, serhii-shkodenko commented
> Отметьте, пожалуйста, с помощью кнопки "Resolve conversation" исправленные комментарии.

Прошу прощения, не обновился интерфейс. Все ок.

2020-11-16 16:15 UTC, serhii-shkodenko requested changes

2020-11-16 16:15 UTC, serhii-shkodenko commented on Task4/XUnitTest/Controllers/CategoryControllerTest.cs
> +        public async Task WalkCategories_IfTruParseReturnFalse_ReturnFalse()
Что-то с именем метода не то в части `IfTruParseReturnFalse`.

2020-11-16 16:41 UTC, serhii-shkodenko requested changes

2020-11-16 16:41 UTC, serhii-shkodenko commented on Task4/HomeTask4.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "HomeTask4.Test", "XUnitTest\HomeTask4.Test.csproj", "{BEAC6BD6-1CB7-4305-85EA-014D50BEEF77}"
По-хорошему папку тоже надо переименовать.

2020-11-16 16:41 UTC, serhii-shkodenko commented on Task4/XUnitTest/Entities/RecipeTest.cs
> +        public async void CTOR_Recipe_IfDataCorrect_CreateEntity()
Я не вижу, зачем здесь `async`. Егоможно удалить.

2020-11-16 16:41 UTC, serhii-shkodenko commented on Task4/XUnitTest/Entities/RecipeTest.cs
> +        public async void CTOR_Recipe_IfDataCorrect_CreateEntity()
Согласно [конвенции](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions), имя метода должно быть в `PascalCase`. Слово Constructor лучше написать полностью.

2020-11-16 17:28 UTC, serhii-shkodenko commented on Task4/XUnitTest/Controllers/CategoryControllerTest.cs
> +        }
Для случая, когда `int.TryParse` возвращает `false` Вы добавили тест, а для случая, когда `CurrentCategory is null`, что демонстрирует этот скриншот с покрытием Вашего кода. Добавьте, пожалуйста. 

![method_coverage](https://user-images.githubusercontent.com/69808191/99286564-b7688e00-2841-11eb-92d1-0f8405a2f131.png)

Красным подсвечиваются непокрытые участки кода, оранжевым - частично покрытые.

2020-11-16 17:37 UTC, Vakhaa commented on Task4/XUnitTest/Controllers/CategoryControllerTest.cs
> +        }
Точно, забыл. Я переделал)

2020-11-16 21:19 UTC, serhii-shkodenko requested changes

2020-11-16 21:19 UTC, serhii-shkodenko commented on Task4/HomeTask4.Tests/Controllers/CategoryControllerTest.cs
> +        readonly Mock<IUnitOfWork> _unitOfWorkMock; // Create mock object for IUnitOfWork
И конечно модификаторы `private` добавьте в аналогичных местах по всему проекту.

2020-11-16 21:19 UTC, serhii-shkodenko commented on Task4/HomeTask4.Tests/Controllers/RecipeControllerTest.cs
> +        }
Этот тест можно немного улучшить, сделав ожидание более специфичным. Можно проверить, что в метод был передан не просто любой список, а список с ожидаемым количеством элементов.
![test_refine](https://user-images.githubusercontent.com/69808191/99308664-f6f2a280-2860-11eb-85dc-b9f698c89786.png)

2020-11-16 21:19 UTC, serhii-shkodenko commented on Task4/HomeTask4.Tests/Controllers/RecipeControllerTest.cs
> +            _repositoryMock.Verify(o => o.AddRangeAsync(It.IsAny<List<IngredientsInRecipe>>()), Times.Exactly(1));
Зачем использовать `Times.Exactly(1)`, если есть `Times.Once`.

2020-11-16 21:19 UTC, serhii-shkodenko commented on Task4/HomeTask4.Tests/Controllers/RecipeControllerTest.cs
> +            MakeMockGetWithIncludeListForRepository();
Для работы этого теста настройка ожидания, содержащаяся в этом методе, не нужна. Удалите.

2020-11-16 21:19 UTC, serhii-shkodenko commented on Task4/HomeTask4.Tests/Controllers/RecipeControllerTest.cs
> +        private void MakeMockGetWithIncludeListForRepository()
Хорошо, что Вы попытались по максимуму сократить количество кода, необходимое для работы тестов, и вынесли повторяющиеся действия в отдельные приватные методы. Однако поскольку Вы делаете настройку ожидания, будет не лишним его проверить в блоке Assert. Возможно, Вам подойдет метод `VerifyAll()`, вызванный на `_repositoryMock`. Просмотрите все тесты и предложите решение.

2020-11-18 21:21 UTC, serhii-shkodenko requested changes

2020-11-18 21:21 UTC, serhii-shkodenko commented on Task4/HomeTask4.Tests/Controllers/CategoryControllerTest.cs
> +        public async Task WalkCategories_IfItemExistsAndCurrentCategoryIsNull_ReturnTrue()
Имя метода в конце содержит ReturnTrue, но Вы проверяете `Assert.False(resultBool)`.

2020-11-18 21:21 UTC, serhii-shkodenko commented on Task4/HomeTask4.Tests/Controllers/CategoryControllerTest.cs
> +            var expected = "expected";
Это имя переменной ничего не говорит, ее лучше назвать `expectedCategoryName`.

2020-11-18 21:21 UTC, serhii-shkodenko commented on Task4/HomeTask4.Tests/Controllers/RecipeControllerTest.cs
> +            Assert.Equal(1, _controller.CurrentRecipe.CategoryId);
Следует избегать использования подобных чисел, происхождение которых нельзся сразу распознать. С единицей все более-менее понятно, это `Id` категории, который был передан в метод, а вот почему Вы сравниваете `CurrentRecipe.Id` с `0` это вопрос. Если Вы сравниваете с дефолтным значением для типа `int`, то такая проверка не нужна.

2020-11-18 21:21 UTC, serhii-shkodenko commented on Task4/HomeTask4.Tests/Controllers/CategoryControllerTest.cs
> +        }
Вот код Вашего метода: 
```
public async Task<bool> WalkCategoriesAsync(string answer)
{
        if (int.TryParse(answer, out int categoryId))
        {
            await SetCurrentCategoryAsync(categoryId);
                if (CurrentCategory == null) //Если пользователь дал неверный id дочерней категории
                    return false;
            return true;
        }
        else
        {
            return false;
        }
}
```
Внутри `SetCurrentCategoryAsync()` происходит вызов метода `GetWithIncludeListAsync()`, однако Вы его не настраиваете. Вы **надеетесь**, что поскольку `GetWithIncludeListAsync()` Вы не настраиваете, а `CurrentCategory` по умолчанию равна `null`, то все буде хорошо. 

Однако, юнит тест не должен зависеть от внешних обстоятельств. Например, в будущем Вы можете инициализировать `CurrentCategory`, тогда Ваш тест будет падать, хотя непосредственно в тестируемом методе ничего не менялось. Если `GetWithIncludeListAsync()` может в результате своей работы вернуть null, тогда соответствующим образом настройте его, а ожидание проверьте.

2020-11-18 21:21 UTC, serhii-shkodenko commented on Task4/HomeTask4.Tests/Controllers/RecipeControllerTest.cs
> +            Assert.Equal("expected", _controller.CurrentRecipe.Description);
Тоже  сразу неясно, почему сравниваете с `expected`. Лучше присвойте это значение переменной с говорящим названием, с сравнивайте уже с ней.

2020-11-19 21:20 UTC, serhii-shkodenko requested changes

2020-11-19 21:20 UTC, serhii-shkodenko commented on Task4/HomeTask4.Tests/Controllers/CategoryControllerTest.cs
> +        }
Ваши ожидания для моков не работают, Вы не настроили возвращение `null`. Я инициализировал `CurrentCategory` в конструкторе контроллера и упали два теста.
![Tests_Failing](https://user-images.githubusercontent.com/69808191/99725183-6533a100-2abd-11eb-9eff-b3e68f93b9f7.jpg)

Упавшие тесты:

- WalkCategories_IfTryParseReturnFalse_ReturnFalse;
- AddChild_IfTryParseReturnTrue_ReturnNull.

Чтобы мок в ответ на обращение к методу вернул `null`, добавьте `ReturnsAsync((YourTypeCastTo)null);`.

2020-11-19 21:39 UTC, Vakhaa commented
В этих методах лишняя проверка в CurrentCategory на null. Так, как весь код внутри обернут в if с Int.TryParse.

2020-11-19 22:10 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Дождитесь ревью @alex-geraschenko и потом можно будет смержить.

2020-11-23 14:40 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-11-23 14:54 UTC, merged